# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: iporer
email: raohongrui@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  本站记录我的前端之旅,纪念我逝去的青春.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iporer.github.io/" # the base hostname & protocol for your site
twitter_username: iporer
github_username: iporer
facebook_username: iporer
linkedIn_username: iporer

# Build settings
markdown: kramdown
